HotelManager/Models/Region.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelManager.Models
{
    public class Region
    {
        public int ID { get; set; }
        public string Slug { get; set; }
        public int LocationID { get; set; }
        public string RegionName { get; set; }
        public string RegionSummary { get; set; }
        public string RegionDescription { get; set; }

        public virtual Location Location { get; set; }

        public virtual ICollection<Town> Towns { get; set; }
    }
}

HotelManager/Controllers/RegionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelManager.DAL;
using HotelManager.Models;

namespace HotelManager.Controllers
{
    public class RegionsController : Controller
    {
        private HotelManagerContext db = new HotelManagerContext();

        // GET: Regions
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Regions.ToList());
        }

        // GET: Regions/Details/5
        /*public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }*/

        [AllowAnonymous]
        public ActionResult Details(string slug)
        {
            if (slug == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Region region = db.Regions.SingleOrDefault(p => p.Slug.ToLower().Equals(slug.ToLower()));
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // GET: Regions/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Create([Bind(Include = "ID,Slug,RegionName,RegionSummary,RegionDescription")] Region region)
        {
            if (ModelState.IsValid)
            {
                db.Regions.Add(region);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(region);
        }

        // GET: Regions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // POST: Regions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit([Bind(Include = "ID,Slug,RegionName,RegionSummary,RegionDescription")] Region region)
        {
            if (ModelState.IsValid)
            {
                db.Entry(region).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(region);
        }

        // GET: Regions/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // POST: Regions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            Region region = db.Regions.Find(id);
            db.Regions.Remove(region);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HotelManager/Controllers/TownsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelManager.DAL;
using HotelManager.Models;

namespace HotelManager.Controllers
{
    public class TownsController : Controller
    {
        private HotelManagerContext db = new HotelManagerContext();

        // GET: Towns
        [AllowAnonymous]
        public ActionResult Index()
        {
           
            return View();
        }

        // GET: Towns/Details/5
        [AllowAnonymous]
        public ActionResult Details(string slug)
        {
            if (slug == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Town town = db.Towns.SingleOrDefault(p => p.Slug.ToLower().Equals(slug.ToLower()));
            if (town == null)
            {
                return HttpNotFound();
            }


            Region region = db.Regions.Find(town.RegionID);
            if (region == null)
            {
                town.RegionSlug = "";
                town.RegionName = "";
            }
            else
            {
                town.RegionSlug = region.Slug;
                town.RegionName = region.RegionName;
            }


            return View(town);
        }

        // GET: Towns/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            ViewBag.RegionID = new SelectList(db.Regions, "ID", "Slug");
            return View();
        }

        // POST: Towns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Create([Bind(Include = "ID,Slug,RegionID,RegionSlug,RegionName,TownName,TownSummary,TownDescription,SletohID,Show")] Town town)
        {
            if (ModelState.IsValid)
            {
                db.Towns.Add(town);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RegionID = new SelectList(db.Regions, "ID", "Slug", town.RegionID);
            return View(town);
        }

        // GET: Towns/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Town town = db.Towns.Find(id);
            if (town == null)
            {
                return HttpNotFound();
            }
            ViewBag.RegionID = new SelectList(db.Regions, "ID", "Slug", town.RegionID);
            return View(town);
        }

        // POST: Towns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit([Bind(Include = "ID,Slug,RegionID,RegionSlug,RegionName,TownName,TownSummary,TownDescription,SletohID,Show")] Town town)
        {
            if (ModelState.IsValid)
            {
                db.Entry(town).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RegionID = new SelectList(db.Regions, "ID", "Slug", town.RegionID);
            return View(town);
        }

        // GET: Towns/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Town town = db.Towns.Find(id);
            if (town == null)
            {
                return HttpNotFound();
            }
            return View(town);
        }

        // POST: Towns/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "canEdit")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Town town = db.Towns.Find(id);
            db.Towns.Remove(town);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HotelManager/Views/Regions/Create.cshtml
@model HotelManager.Models.Region

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Region</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionSummary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HotelManager/Views/Regions/Delete.cshtml
@model HotelManager.Models.Region

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Region</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelManager/Views/Regions/Details.cshtml
@model HotelManager.Models.Region
@using HotelManager.Helpers;
@{
    ViewBag.Title = "Details";
}

<h2>@Model.RegionName</h2>

<div>
    <p>
        @{
            if (ViewContext.HttpContext.User.IsInRole("canEditAll"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.ID })
            }
        }
    </p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Slug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionSummary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionSummary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionDescription)
        </dd>

    </dl>


    @{
        if (Model.Towns.Count > 0)
        {
            <ul>
                @{
            foreach (var item in Model.Towns)
            {
                <li>@Html.ActionLink(item.TownName, "Details", "Towns", new { slug = presentationHelper.Slugify(item.Slug) }, null)</li>
            }
                }
            </ul>
        }

    }

</div>

HotelManager/Views/Regions/Edit.cshtml
@model HotelManager.Models.Region

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Region</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionSummary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionSummary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionSummary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HotelManager/Views/Regions/Index.cshtml
@model IEnumerable<HotelManager.Models.Region>
@using HotelManager.Helpers;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @{
        if (ViewContext.HttpContext.User.IsInRole("canEditAll"))
        {
            @Html.ActionLink("Create New Region", "Create")
        }
    }

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Slug)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegionSummary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegionDescription)
        </th>
        <th></th>
    </tr>

@{
    foreach (var item in Model) 
    {
    <tr>
        <td>
            @Html.ActionLink(item.RegionName, "Details", new { slug = presentationHelper.Slugify(item.Slug) })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegionSummary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegionDescription)
        </td>
        <td>
        @{

            if (ViewContext.HttpContext.User.IsInRole("canEditAll"))
            {
                @Html.ActionLink("Edit", "Edit", new { id=item.ID })
                @: |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            }
        }
                </td>
            </tr>
       
    }
}
</table>